name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
#     paths:
#    - gradle.properties
#    - package_info.json

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      docker-username: ${{ github.repository_owner }}
    secrets:
      docker-password: ${{ secrets.CR_PAT }}